inherit_gem:
  rubocop-govuk:
    - config/default.yml

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'bin/**/*'

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/EndOfLine:
  EnforcedStyle: lf

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*_spec.rb'
