name: Deploy to GOV.UK PaaS

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '0 6 * * *'

jobs:
  create-artifacts:
    name: Create entity relationship artifacts

    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOSTNAME: localhost
      DB_PORT: 5432
      ANALYTICS_DB_USERNAME: postgres
      ANALYTICS_DB_PASSWORD: postgres
      ANALYTICS_DB_HOSTNAME: localhost
      ANALYTICS_DB_PORT: 5432

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: DFE-Digital/early-careers-framework

      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.101.0
        with:
          bundler-cache: true
          ruby-version: '3.1.2'

      - name: Install rails-erd
        run: |
          bundle config unset deployment
          bundle add rails-erd

      - name: Set up test database
        run: bin/rails db:create db:schema:load

      - name: create erd config file
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./.erdconfig
          contents: |
            attributes:
              - content
            disconnected: false
            filename: tmp/entity-relationship-diagram
            filetype: pdf
            indirect: false
            inheritance: false
            markup: true
            notation: bachman
            orientation: vertical
            polymorphism: false
            sort: true
            warn: false
            title: Teacher Continuing Professional Development - ERD
            exclude:
              - Record
              - ApplicationRecord
              - DiscardableRecord
              - Item
              - ApiToken
              - NPQRegistrationApiToken
              - EngageAndLearnApiToken
              - LeadProviderApiToken
              - DataStudioApiToken
              - PaperTrail::Version
              - ActiveRecord::SessionStore::Session
              - ActiveStorage::Record
              - ActiveStorage::Blob
              - ActiveStorage::VariantRecord
              - ActiveStorage::Attachment
              - Delayed::Backend::ActiveRecord::Job
              - Analytics::BaseRecord
              - Feature
              - Feature::SelectedObject
              - DataStage::SchoolLink
              - DataStage::School
              - DataStage::SchoolChange
              - ActionMailbox::Record
              - ActionMailbox::InboundEmail
              - AdminProfile
              - AdditionalSchoolEmail
              - NominationEmail
              - PartnershipNotificationEmail
              - PartnershipCsvUpload
              - PrivacyPolicy::Acceptance
              - PrivacyPolicy
              - Email
              - Email::Association
              - Owner
              - EventLog
              - ApiRequest
              - ApiRequestAudit
              - InductionCoordinatorProfile
              - FinanceProfile
              - LeadProviderProfile
              - DeliveryPartnerProfile
              - InductionCoordinatorProfilesSchool
              - Finance::Statement::ECF::Paid
              - Finance::Statement::ECF::Payable
              - Finance::Statement::NPQ::Paid
              - Finance::Statement::NPQ::Payable
              - Finance::Schedule::NPQLeadership
              - Finance::Schedule::NPQSpecialist
              - Finance::Schedule::NPQSupport
              - Finance::Schedule::ECF
              - Finance::Schedule::Mentor
              - Finance::Schedule::NPQ
              - Finance::Schedule::NPQEhco
            only: null
            only_recursion_depth: null
            prepend_primary: false
            cluster: true
            splines: curved
          write-mode: overwrite

      - name: Create ERD DOT
        run: bundle exec erd --filetype=dot

      - name: Create ERD PDF
        run: bundle exec erd --filetype=pdf

      - name: Create ERD PNG
        run: bundle exec erd --filetype=png

      - name: Publish diagrams
        uses: actions/upload-artifact@v2
        with:
          name: Teacher CPD - entity relationship Diagram
          path: ./tmp/entity-relationship-diagram.*

  update-diagrams:
    name: Update entity relationship artifacts

    runs-on: ubuntu-latest

    needs: create-artifacts

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get diagrams
        uses: actions/download-artifact@v2
        with:
          name: Teacher CPD - entity relationship Diagram
          path: ./source/images

      - name: Push updated diagram
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "updated entity relationship diagram"
          git pull --rebase
          git push

  build-and-push:
    name: Build and deploy service manual

    runs-on: ubuntu-latest

    needs: update-diagrams

    steps:
    - uses: DFE-Digital/github-actions/turnstyle@master
      name: Check workflow concurrency
      with:
        initial-wait-seconds: 15
        poll-interval-seconds: 15
        abort-after-seconds: 300
        same-branch-only: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.101.0
      with:
        bundler-cache: true
        ruby-version: '3.1.2'

    - name: Validate C4 Models
      run: ./bin/c4-validate.sh

    - name: Generate C4 Views
      run: ./bin/c4-to-plantuml.sh

    - name: Generate Images and documents for C4 views
      run: ./bin/plantuml-to-png.sh

    - name: Build docs with middleman
      run: make build

    - name: Set environment variables (Push)
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        SPACE=earlycareers-framework-dev
        echo "SPACE=${SPACE}" >> $GITHUB_ENV
        APP_NAME=cpd-service-manual
        echo "APP_NAME=${APP_NAME}" >> $GITHUB_ENV

    - name: Set environment variables (Pull request)
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        SPACE=earlycareers-framework-dev
        echo "SPACE=${SPACE}" >> $GITHUB_ENV
        APP_NAME=cpd-service-manual-${{ github.event.number }}
        echo "APP_NAME=${APP_NAME}" >> $GITHUB_ENV

    - name: Configure Cloud Foundry CLI with space ${{ env.SPACE }}
      uses: DFE-Digital/github-actions/setup-cf-cli@master
      with:
        CF_USERNAME: ${{ secrets.CF_USERNAME }}
        CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
        CF_SPACE_NAME: ${{ env.SPACE }}

    - name: Push ${{ env.APP_NAME }} to GOV.UK PaaS
      run: cf push -p build -b staticfile_buildpack --disk 128M --memory 64M ${{ env.APP_NAME }}

    - name: Post comment to Pull Request ${{ github.event.number }}
      if: ${{ github.event_name == 'pull_request' }}
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: Review app deployed to <https://${{ env.APP_NAME }}.london.cloudapps.digital>
