name: Update package dependencies

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  update-dependencies:
    name: Update dependencies

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: DFE-Digital/early-careers-framework

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.101.0
        with:
          bundler-cache: true
          ruby-version: '3.1.2'
          
      - name: Unlock bundler
        run: bundle config unset deployment

      - name: Run bundler update
        run: bundle update

      - name: Build docs with middleman
        run: make build

      - name: Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updated dependency packages"
          git pull --rebase
          git push
